steps:
  # Step 1: Install dependencies
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: bash
    args:
      ["-c", "cp -r frontend/build build"]
    dir: "frontend"
    volumes:
      - name: "npm-cache"
        path: /root/.npm

  # Step 2: Build frontend dengan injeksi VITE_API_URL
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: bash
    args:
      - -c
      - |
        npm run build
    dir: "frontend"
    volumes:
      - name: "npm-cache"
        path: /root/.npm

  # Step 3: Deploy ke App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["app", "deploy", "--quiet"]
    dir: "frontend"

options:
  logging: CLOUD_LOGGING_ONLY
